name=RoboKosonsoy Link
version=0.1.0
author=RoboKosonsoy Community
maintainer=RoboKosonsoy
sentence=Long-range communication library for EBYTE E32 LoRa modules.
paragraph=Reliable communication library for Arduino and ESP32 using EBYTE E32 modules.
category=Communication
url=https://github.com/RoboKosonsoy/RoboKosonsoy-Link
architectures=*
includes=RKL.h
license=MIT